# golangci-lint v2.4.0 configuration
# Adapted from parable-api
version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  default: none
  enable:
    # Core linters
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional useful linters
    - misspell
    - unconvert

  settings:
    errcheck:
      # Ignore error checking for these patterns
      check-blank: false
      check-type-assertions: false
      exclude-functions:
        # Ignore fmt print functions
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Print
        - fmt.Printf
        - fmt.Println
        # Ignore HTTP response writing
        - (net/http.ResponseWriter).Write
        - (github.com/labstack/echo/v4.Context).String
        - (github.com/labstack/echo/v4.Context).NoContent
        # Ignore JSON encoding in HTTP handlers
        - (*encoding/json.Encoder).Encode
        # Ignore Close in defer statements
        - (io.Closer).Close
        - (*os.File).Close
        - (*net/http.Response.Body).Close
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Stmt).Close
        - (*database/sql.Tx).Rollback
        - (*encoding/csv.Writer).Write
        - (*os.File).Seek
        - os.Remove
        - os.RemoveAll
        # Ignore our storage wrapper Close
        - (*github.com/loganlanou/logans3d-v4/storage.Storage).Close
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Pedantic struct field ordering
        - shadow          # Variable shadowing often intentional
    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G115  # Integer overflow conversion
        - G304  # File path provided as taint input (false positives for config files)
        - G306  # Poor file permissions (non-critical for config files)
        - G301  # Directory permissions (0755 is acceptable for upload dirs)
        - G107  # URL provided as taint input (false positives for API calls)

  exclusions:
    generated: strict
    paths:
      - scripts/  # Scripts use weak random for test data generation
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
      # Exclude generated files
      - path: _templ\.go$
        linters:
          - all
      - path: storage/db/.*\.go$
        linters:
          - all
      # Exclude scripts from all linting
      - path: scripts/.*\.go$
        linters:
          - all

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
