// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AdminUser struct {
	ID           string       `db:"id" json:"id"`
	Email        string       `db:"email" json:"email"`
	PasswordHash string       `db:"password_hash" json:"password_hash"`
	Name         string       `db:"name" json:"name"`
	IsActive     sql.NullBool `db:"is_active" json:"is_active"`
	CreatedAt    sql.NullTime `db:"created_at" json:"created_at"`
	LastLoginAt  sql.NullTime `db:"last_login_at" json:"last_login_at"`
}

type CartItem struct {
	ID               string         `db:"id" json:"id"`
	SessionID        sql.NullString `db:"session_id" json:"session_id"`
	UserID           sql.NullString `db:"user_id" json:"user_id"`
	ProductID        string         `db:"product_id" json:"product_id"`
	ProductVariantID sql.NullString `db:"product_variant_id" json:"product_variant_id"`
	Quantity         int64          `db:"quantity" json:"quantity"`
	CreatedAt        sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt        sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type Category struct {
	ID           string         `db:"id" json:"id"`
	Name         string         `db:"name" json:"name"`
	Slug         string         `db:"slug" json:"slug"`
	Description  sql.NullString `db:"description" json:"description"`
	ParentID     sql.NullString `db:"parent_id" json:"parent_id"`
	DisplayOrder sql.NullInt64  `db:"display_order" json:"display_order"`
	CreatedAt    sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt    sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type CollectionItem struct {
	ID           string         `db:"id" json:"id"`
	CollectionID string         `db:"collection_id" json:"collection_id"`
	ProductID    string         `db:"product_id" json:"product_id"`
	Quantity     sql.NullInt64  `db:"quantity" json:"quantity"`
	Notes        sql.NullString `db:"notes" json:"notes"`
	CreatedAt    sql.NullTime   `db:"created_at" json:"created_at"`
}

type Event struct {
	ID          string         `db:"id" json:"id"`
	Title       string         `db:"title" json:"title"`
	Description sql.NullString `db:"description" json:"description"`
	Location    sql.NullString `db:"location" json:"location"`
	Address     sql.NullString `db:"address" json:"address"`
	StartDate   time.Time      `db:"start_date" json:"start_date"`
	EndDate     sql.NullTime   `db:"end_date" json:"end_date"`
	Url         sql.NullString `db:"url" json:"url"`
	IsActive    sql.NullBool   `db:"is_active" json:"is_active"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type Order struct {
	ID                    string         `db:"id" json:"id"`
	UserID                sql.NullString `db:"user_id" json:"user_id"`
	CustomerEmail         string         `db:"customer_email" json:"customer_email"`
	CustomerName          string         `db:"customer_name" json:"customer_name"`
	CustomerPhone         sql.NullString `db:"customer_phone" json:"customer_phone"`
	BillingAddressLine1   string         `db:"billing_address_line1" json:"billing_address_line1"`
	BillingAddressLine2   sql.NullString `db:"billing_address_line2" json:"billing_address_line2"`
	BillingCity           string         `db:"billing_city" json:"billing_city"`
	BillingState          string         `db:"billing_state" json:"billing_state"`
	BillingPostalCode     string         `db:"billing_postal_code" json:"billing_postal_code"`
	BillingCountry        string         `db:"billing_country" json:"billing_country"`
	ShippingAddressLine1  string         `db:"shipping_address_line1" json:"shipping_address_line1"`
	ShippingAddressLine2  sql.NullString `db:"shipping_address_line2" json:"shipping_address_line2"`
	ShippingCity          string         `db:"shipping_city" json:"shipping_city"`
	ShippingState         string         `db:"shipping_state" json:"shipping_state"`
	ShippingPostalCode    string         `db:"shipping_postal_code" json:"shipping_postal_code"`
	ShippingCountry       string         `db:"shipping_country" json:"shipping_country"`
	SubtotalCents         int64          `db:"subtotal_cents" json:"subtotal_cents"`
	TaxCents              int64          `db:"tax_cents" json:"tax_cents"`
	ShippingCents         int64          `db:"shipping_cents" json:"shipping_cents"`
	TotalCents            int64          `db:"total_cents" json:"total_cents"`
	StripePaymentIntentID sql.NullString `db:"stripe_payment_intent_id" json:"stripe_payment_intent_id"`
	StripeCustomerID      sql.NullString `db:"stripe_customer_id" json:"stripe_customer_id"`
	Status                sql.NullString `db:"status" json:"status"`
	FulfillmentStatus     sql.NullString `db:"fulfillment_status" json:"fulfillment_status"`
	PaymentStatus         sql.NullString `db:"payment_status" json:"payment_status"`
	Notes                 sql.NullString `db:"notes" json:"notes"`
	CreatedAt             sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt             sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type OrderItem struct {
	ID               string         `db:"id" json:"id"`
	OrderID          string         `db:"order_id" json:"order_id"`
	ProductID        string         `db:"product_id" json:"product_id"`
	ProductVariantID sql.NullString `db:"product_variant_id" json:"product_variant_id"`
	Quantity         int64          `db:"quantity" json:"quantity"`
	UnitPriceCents   int64          `db:"unit_price_cents" json:"unit_price_cents"`
	TotalPriceCents  int64          `db:"total_price_cents" json:"total_price_cents"`
	ProductName      string         `db:"product_name" json:"product_name"`
	ProductSku       sql.NullString `db:"product_sku" json:"product_sku"`
	CreatedAt        sql.NullTime   `db:"created_at" json:"created_at"`
}

type Product struct {
	ID                 string         `db:"id" json:"id"`
	Name               string         `db:"name" json:"name"`
	Slug               string         `db:"slug" json:"slug"`
	Description        sql.NullString `db:"description" json:"description"`
	ShortDescription   sql.NullString `db:"short_description" json:"short_description"`
	PriceCents         int64          `db:"price_cents" json:"price_cents"`
	CategoryID         sql.NullString `db:"category_id" json:"category_id"`
	Sku                sql.NullString `db:"sku" json:"sku"`
	StockQuantity      sql.NullInt64  `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold  sql.NullInt64  `db:"low_stock_threshold" json:"low_stock_threshold"`
	WeightGrams        sql.NullInt64  `db:"weight_grams" json:"weight_grams"`
	DimensionsLengthMm sql.NullInt64  `db:"dimensions_length_mm" json:"dimensions_length_mm"`
	DimensionsWidthMm  sql.NullInt64  `db:"dimensions_width_mm" json:"dimensions_width_mm"`
	DimensionsHeightMm sql.NullInt64  `db:"dimensions_height_mm" json:"dimensions_height_mm"`
	LeadTimeDays       sql.NullInt64  `db:"lead_time_days" json:"lead_time_days"`
	IsActive           sql.NullBool   `db:"is_active" json:"is_active"`
	IsFeatured         sql.NullBool   `db:"is_featured" json:"is_featured"`
	CreatedAt          sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt          sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type ProductImage struct {
	ID           string         `db:"id" json:"id"`
	ProductID    string         `db:"product_id" json:"product_id"`
	ImageUrl     string         `db:"image_url" json:"image_url"`
	AltText      sql.NullString `db:"alt_text" json:"alt_text"`
	DisplayOrder sql.NullInt64  `db:"display_order" json:"display_order"`
	IsPrimary    sql.NullBool   `db:"is_primary" json:"is_primary"`
	CreatedAt    sql.NullTime   `db:"created_at" json:"created_at"`
}

type ProductVariant struct {
	ID                   string         `db:"id" json:"id"`
	ProductID            string         `db:"product_id" json:"product_id"`
	Name                 string         `db:"name" json:"name"`
	Sku                  sql.NullString `db:"sku" json:"sku"`
	PriceAdjustmentCents sql.NullInt64  `db:"price_adjustment_cents" json:"price_adjustment_cents"`
	StockQuantity        sql.NullInt64  `db:"stock_quantity" json:"stock_quantity"`
	IsDefault            sql.NullBool   `db:"is_default" json:"is_default"`
	CreatedAt            sql.NullTime   `db:"created_at" json:"created_at"`
}

type QuoteFile struct {
	ID               string       `db:"id" json:"id"`
	QuoteRequestID   string       `db:"quote_request_id" json:"quote_request_id"`
	Filename         string       `db:"filename" json:"filename"`
	OriginalFilename string       `db:"original_filename" json:"original_filename"`
	FilePath         string       `db:"file_path" json:"file_path"`
	FileSize         int64        `db:"file_size" json:"file_size"`
	MimeType         string       `db:"mime_type" json:"mime_type"`
	CreatedAt        sql.NullTime `db:"created_at" json:"created_at"`
}

type QuoteRequest struct {
	ID                 string         `db:"id" json:"id"`
	CustomerName       string         `db:"customer_name" json:"customer_name"`
	CustomerEmail      string         `db:"customer_email" json:"customer_email"`
	CustomerPhone      sql.NullString `db:"customer_phone" json:"customer_phone"`
	ProjectDescription string         `db:"project_description" json:"project_description"`
	Quantity           sql.NullInt64  `db:"quantity" json:"quantity"`
	MaterialPreference sql.NullString `db:"material_preference" json:"material_preference"`
	FinishPreference   sql.NullString `db:"finish_preference" json:"finish_preference"`
	DeadlineDate       sql.NullTime   `db:"deadline_date" json:"deadline_date"`
	BudgetRange        sql.NullString `db:"budget_range" json:"budget_range"`
	Status             sql.NullString `db:"status" json:"status"`
	AdminNotes         sql.NullString `db:"admin_notes" json:"admin_notes"`
	QuotedPriceCents   sql.NullInt64  `db:"quoted_price_cents" json:"quoted_price_cents"`
	CreatedAt          sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt          sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID        string         `db:"id" json:"id"`
	Email     string         `db:"email" json:"email"`
	Name      string         `db:"name" json:"name"`
	GoogleID  sql.NullString `db:"google_id" json:"google_id"`
	AvatarUrl sql.NullString `db:"avatar_url" json:"avatar_url"`
	CreatedAt sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type UserCollection struct {
	ID               string         `db:"id" json:"id"`
	UserID           string         `db:"user_id" json:"user_id"`
	Name             string         `db:"name" json:"name"`
	Description      sql.NullString `db:"description" json:"description"`
	IsQuoteRequested sql.NullBool   `db:"is_quote_requested" json:"is_quote_requested"`
	QuoteRequestID   sql.NullString `db:"quote_request_id" json:"quote_request_id"`
	CreatedAt        sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt        sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type UserFavorite struct {
	ID        string       `db:"id" json:"id"`
	UserID    string       `db:"user_id" json:"user_id"`
	ProductID string       `db:"product_id" json:"product_id"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

type UserSession struct {
	ID           string       `db:"id" json:"id"`
	UserID       string       `db:"user_id" json:"user_id"`
	SessionToken string       `db:"session_token" json:"session_token"`
	ExpiresAt    time.Time    `db:"expires_at" json:"expires_at"`
	CreatedAt    sql.NullTime `db:"created_at" json:"created_at"`
}
