// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id string) error
	DeleteProduct(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetCategory(ctx context.Context, id string) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetProduct(ctx context.Context, id string) (Product, error)
	GetProductBySlug(ctx context.Context, slug string) (Product, error)
	GetProductImages(ctx context.Context, productID string) ([]ProductImage, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoriesByParent(ctx context.Context, parentID sql.NullString) ([]Category, error)
	ListFeaturedProducts(ctx context.Context) ([]Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListProductsByCategory(ctx context.Context, categoryID sql.NullString) ([]Product, error)
	ListRootCategories(ctx context.Context) ([]Category, error)
	ListUsers(ctx context.Context) ([]User, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
