// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddFavorite(ctx context.Context, arg AddFavoriteParams) (UserFavorite, error)
	AddToCart(ctx context.Context, arg AddToCartParams) error
	AddToCollection(ctx context.Context, arg AddToCollectionParams) (CollectionItem, error)
	ClearCart(ctx context.Context, arg ClearCartParams) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (UserCollection, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id string) error
	DeleteCollection(ctx context.Context, arg DeleteCollectionParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteProduct(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, sessionToken string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	GetCartBySession(ctx context.Context, sessionID sql.NullString) ([]GetCartBySessionRow, error)
	GetCartByUser(ctx context.Context, userID sql.NullString) ([]GetCartByUserRow, error)
	GetCartItemCount(ctx context.Context, arg GetCartItemCountParams) (interface{}, error)
	GetCartTotal(ctx context.Context, arg GetCartTotalParams) (interface{}, error)
	GetCategory(ctx context.Context, id string) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetCollection(ctx context.Context, arg GetCollectionParams) (UserCollection, error)
	GetCollectionItems(ctx context.Context, collectionID string) ([]GetCollectionItemsRow, error)
	GetExistingCartItem(ctx context.Context, arg GetExistingCartItemParams) (GetExistingCartItemRow, error)
	GetFavoriteCount(ctx context.Context, userID string) (int64, error)
	GetProduct(ctx context.Context, id string) (Product, error)
	GetProductBySlug(ctx context.Context, slug string) (Product, error)
	GetProductImages(ctx context.Context, productID string) ([]ProductImage, error)
	GetSessionByToken(ctx context.Context, sessionToken string) (GetSessionByTokenRow, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error)
	GetUserCollections(ctx context.Context, userID string) ([]GetUserCollectionsRow, error)
	GetUserFavorites(ctx context.Context, userID string) ([]GetUserFavoritesRow, error)
	IsFavorite(ctx context.Context, arg IsFavoriteParams) (int64, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoriesByParent(ctx context.Context, parentID sql.NullString) ([]Category, error)
	ListFeaturedProducts(ctx context.Context) ([]Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListProductsByCategory(ctx context.Context, categoryID sql.NullString) ([]Product, error)
	ListRootCategories(ctx context.Context) ([]Category, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkCollectionAsQuoted(ctx context.Context, arg MarkCollectionAsQuotedParams) error
	MergeCartOnLogin(ctx context.Context, arg MergeCartOnLoginParams) error
	RemoveCartItem(ctx context.Context, id string) error
	RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error
	RemoveFromCollection(ctx context.Context, arg RemoveFromCollectionParams) error
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (UserCollection, error)
	UpdateCollectionItem(ctx context.Context, arg UpdateCollectionItemParams) (CollectionItem, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
